name       : kwayland
version    : 5.50.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kwayland-5.50.0.tar.xz : 0baf139c61ae385b767077ea10515f7e95d8747e8c2af3883472eb54b6c63708
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
