name       : kwayland
version    : 5.36.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.36/kwayland-5.36.0.tar.xz : a2c473c7f5cefc87b5b63813fa1373c43c1c8374423fb85fe1c187b553453341
license    : LGPL-2.1
component  : programming
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
