name       : kwayland
version    : 5.49.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kwayland-5.49.0.tar.xz : 26e2e56877b0e174d523f67fa2ec1720b6e16026fc145b029bbd0739a2a02535
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
