name       : kwayland
version    : 5.41.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kwayland-5.41.0.tar.xz : 7661b91d39a268a4cd95f85be9b88c06fecb7d1a13cbfc1fed101ec9b97982b7
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
