name       : kwayland
version    : 5.68.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kwayland-5.68.0.tar.xz : 7c99bfac8f4bff457a5384c846be776c385649ced76be0f48699c6e12de24e7c
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
