name       : kwayland
version    : 5.39.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.39/kwayland-5.39.0.tar.xz : dd74c8edef9f28dd8f2df9e52a7f32f844d16c342e3184a69a57eb6c0f893029
license    : LGPL-2.1
component  : programming
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
