name       : kwayland
version    : 5.78.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/kwayland-5.78.0.tar.xz : ab6ba414a69b2399ae7b83844d9ea735cd763afc2e5c2a74292b5ae914db4a14
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : programming.library
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(x11)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
