name       : kwayland
version    : 5.48.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kwayland-5.48.0.tar.xz : e46946f0e901b45588f00decbb27bec60d5b7f357e76100ddd6e0815de148be1
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
