name       : kwayland
version    : 5.55.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kwayland-5.55.0.tar.xz : f428ca0defd8109d5b101799d3e16ec0c973afa1a930afb31ce0eef7f1083855
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
