name       : kwayland
version    : 5.63.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kwayland-5.63.0.tar.xz : afcd39152c364a44c85c78e56bcaa5bb70c0a221ecfae3811b14e60a7884e80f
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
