name       : kwayland
version    : 5.54.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kwayland-5.54.0.tar.xz : eec5aa12391a1097b47bdcb25273054081928bb0de1ae1ff198e626428082778
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
