name       : kwayland
version    : 5.57.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kwayland-5.57.0.tar.xz : f00d2997163f559cecf30f5e945d5456628a0d120acafba49fa14af28c22b1d6
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
