name       : kwayland
version    : 5.45.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kwayland-5.45.0.tar.xz : 78e2902520a3d3b13f8db3c5b5ee253c138cfe07934ac3fdd7a3bd87a020625e
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
