name       : kwayland
version    : 5.99.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/kwayland-5.99.0.tar.xz : a7be2125e3a833e99ad9405a03d4f9bec0d4c83c23898406da1daaf068dd65a2
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : programming.library
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
optimize   : lto
builddeps  :
    - pkgconfig(xkbcommon) 
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(x11)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
        - wayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
