name       : kwayland
version    : 5.44.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kwayland-5.44.0.tar.xz : 935ac16624c41850756cbee48548e68da583fb28a63a08f931d760c6677c08df
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
