name       : kwayland
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/kwayland-5.35.0.tar.xz : 3e6472297968e9f60e6ebce9d33e54337f40085dc1ea83e37d8bbccd0f198b70
license    : LGPL-2.1
component  : programming
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
