name       : kwayland
version    : 5.62.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kwayland-5.62.0.tar.xz : c9f513008c91e70b09f5acb76dde332491afde0e94948066c2f1e621bc368eb6
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
