name       : kwayland
version    : 5.67.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kwayland-5.67.0.tar.xz : 91314f19f5c99cd7763656c95362f81635142732feff02f05c554da3f094e168
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
