name       : kwayland
version    : 5.47.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kwayland-5.47.0.tar.xz : dbbdcf05ad00d14931cce83fba968146f46d17053ccd22297a20e2fee9ef2548
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
