name       : kwayland
version    : 5.59.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kwayland-5.59.0.tar.xz : 39ae3b71b452e555ef2715a0b1305d44e52b1913882981f8e2e036f481f3e580
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
