name       : kwayland
version    : 5.75.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kwayland-5.75.0.tar.xz : 4476113932b26484698b09a4653c8ffc9772122f4ada42b0cb327527f8f2d9c0
homepage   : https://community.kde.org/Frameworks
license    : 
    - BSD-3-Clause
    - LGPL-2.1-only
component  : programming.library
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(x11)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
