name       : kwayland
version    : 5.40.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kwayland-5.40.0.tar.xz : 2d4ede706e73c1ec7935595b983c7c9ad52d3c794b5eb0b60d17a056886ba403
license    : LGPL-2.1
component  : programming
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
