name       : kwayland
version    : 5.64.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kwayland-5.64.0.tar.xz : 1540d4ff62afd0bff234e08618fc77d2c54b5cd69bf9c478c45a08a6e69349d3
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
