name       : kwayland
version    : 5.51.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kwayland-5.51.0.tar.xz : e2f6d354e90582720c4631432034db2bc86e3b4db2dae4e2622758d33d5fb6b4
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
