name       : kwayland
version    : 5.60.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kwayland-5.60.0.tar.xz : a0645594c2dc7c121b11eecf1c1d31448d110d13dab200caadddb7e1d836d905
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
