name       : kwayland
version    : 5.74.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kwayland-5.74.0.tar.xz : 27c04e1a77df7af476fdcfcbc175c9078fc636a6ab10fa9cc41c6029400631fb
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(x11)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
