name       : kwayland
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/kwayland-5.32.0.tar.xz : adc011e3cec25aeb920b55d45f81e5866a7a46d3a5979376735980d0f1c1fbcf
license    : LGPL-2.1
component  : programming
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
