name       : kwayland
version    : 5.42.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kwayland-5.42.0.tar.xz : 07dae8ef27b782d51940969fddb08fe79fbd7ce5028603dbe8ba4375eff32673
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
