name       : kwayland
version    : 5.53.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kwayland-5.53.0.tar.xz : 7098628c95f2a47fe8dea8ef7b85179449e2cb13ff94732d9e3375c60647d24c
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
