name       : kwayland
version    : 5.38.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.38/kwayland-5.38.0.tar.xz : 404aaf11e144a42b2422a5a47aaf04fb629c4a468689bd8f543c0de6b745a53d
license    : LGPL-2.1
component  : programming
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
