name       : kwayland
version    : 5.46.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kwayland-5.46.0.tar.xz : d28af10659af8a6970d9a04253d80c29d6098f36cedf85a3a0698ea42eec9bb7
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(wayland-server)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
